//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANCUOIKI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSOVATCHAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COSOVATCHAT()
        {
            this.PHONGTROes = new HashSet<PHONGTRO>();
        }
    
        public string MAVATCHAT { get; set; }
        public string TENVATCHAT { get; set; }
        public Nullable<double> GIAVAtCHAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGTRO> PHONGTROes { get; set; }
    }
}
