//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANCUOIKI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYKKIHD { get; set; }
        public Nullable<System.DateTime> NGAYHETHANHD { get; set; }
        public Nullable<double> TIENCOC { get; set; }
        public string MAPHONG { get; set; }
        public string MAHOADON { get; set; }
        public string MAND { get; set; }
        public string MADV { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual PHONGTRO PHONGTRO { get; set; }
    }
}
