//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANCUOIKI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGTRO()
        {
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public string MAPHONG { get; set; }
        public Nullable<double> DIENTICH { get; set; }
        public Nullable<int> TANG { get; set; }
        public int SOPHONG { get; set; }
        public string TRANGTHAI { get; set; }
        public string LOAIPHONG { get; set; }
        public Nullable<double> GIAPHONG { get; set; }
        public string HINHANH { get; set; }
        public string MAVATCHAT { get; set; }
    
        public virtual COSOVATCHAT COSOVATCHAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
    }
}
