//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANCUOIKI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string MATK { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<System.DateTime> NGAYDANGKI { get; set; }
        public string CHUCVU { get; set; }
        public string MAND { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
